---
kind: pipeline
type: docker
name: default

steps:
- name: package
  image: dtzar/helm-kubectl:3.8.1
  commands:
  - helm version
  - helm dependency update
  - helm package .

- name: push-intermediate
  image: dtzar/helm-kubectl:3.8.1
  commands:
  - echo Packaging...
  
- name: verify
  image: dtzar/helm-kubectl:3.8.1
  commands:
  - echo Verifying...
  
