---
kind: pipeline
type: docker
name: default

steps:
- name: package
  image: dtzar/helm-kubectl:3.8.1
  commands:
  - helm version
  - helm dependency update
  - helm package .

- name: push-intermediate
  image: dtzar/helm-kubectl:3.8.1
  environment:
    github_username:
      from_secret: github_username
    github_password:
      from_secret: github_password
  commands:
  - echo Pushing...
  - ls -la
  
- name: verify
  image: dtzar/helm-kubectl:3.8.1
  commands:
  - echo Verifying...
  
